apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "template.pods-label" . | nindent 4 }}-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      {{- include "template.pods-label" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "template.pods-label" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "template.finalImageName" . }}
          ports:
            - containerPort: {{ .Values.server.port }}