apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  slector:
    {{- include "template.pods-label" | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.server.port }}